server:
    port: 9002

#mysql setting
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-ld6d5-kr.vpc-pub-cdb.ntruss.com:3306/todacdb?serverTimezone=Asia/Seoul
    username: tdDBUser
    password: ncl0ud_TDdbSecret

#JPA setting
#스키마 생성 create:기존테이블삭제후 생성, update:변경된 부분만 반영
  jpa:
    hibernate:
      ddl-auto: update
    #ddl 생성시 데이타베이스 고유의 기능을 사용할 것인가
    generate-ddl: true
    #api 호출시 실행되는 sql 문을 콘솔에 보여줄것인가
    show-sql: true
    #Mysql 상세지정
    database-platform: org.hibernate.dialect.MySQLDialect

# Payment Setting
iamport:
  key: 7035336281076508
  secret: 10NMa46OKhzUMcRzvzIeUBlk9xkX8TMsPT8xNbr8GCvAO7Cg5KLmSvzujHnIA0YMaTk36ArKik3Rvot2
  
--- 
##Login Setting 
#spring:
#  config:
#    activate:
#      on-profile: local
#      
#react:
#  kakao:
#    login:
#      client: 0379f4e17974f898bd38887c56a6c8f7
#      secret: FylAiEmFFOofOmlpSQs806vsYm99ld67
#      redirecturl: http://localhost:3000/login/callback
#      logoutRedirectUrl: http://localhost:3000/login/logoutcallback
#      
#  naver:
#    login:
#      client: 64_rjB9Vr3BUXeAXii_Y
#      secret: QJvtfoXSkD
#      redirecturl: http://localhost:3000/login/callback
#---
#spring:
# config:
#    activate:
#      on-profile: dev
      
react:
  kakao:
    login:
      client: 0379f4e17974f898bd38887c56a6c8f7
      secret: FylAiEmFFOofOmlpSQs806vsYm99ld67
      redirecturl: http://175.45.192.182/login/callback
      logoutRedirectUrl: http://175.45.192.182/login/logoutcallback
      
  naver:
    login:
      client: 64_rjB9Vr3BUXeAXii_Y
      secret: QJvtfoXSkD
      redirecturl: http://175.45.192.182/login/callback